services:
- docker

branches:
  only:
    - master
    - module_11


before_script:
- echo "Test the TODO list"
- docker build --target testing-offline --tag todo-app:devops-course-starter_todoapp-test-offline .
- docker run --env-file .env.test todo-app:devops-course-starter_todoapp-test-offline
- docker build --target testing-online --tag todo-app:devops-course-starter_todoapp-test-online .
- docker run  -e DB_CONNECTION_STRING=$DB_CONNECTION_STRING todo-app:devops-course-starter_todoapp-test-online
      
script: 
- echo "Build the TODO list"
- docker build --target production --tag $DOCKER_USER/todo-app:$TRAVIS_COMMIT .
- docker build --target production --tag $DOCKER_USER/todo-app:latest .

- echo "Push the TODO list to Docker Hub"
- echo $DOCKER_PWD | docker login --username $DOCKER_USER --password-stdin
- docker push $DOCKER_USER/todo-app:$TRAVIS_COMMIT
- docker push $DOCKER_USER/todo-app:latest

- echo "Trigger the push of the app to Azure"
- curl -dH -X POST $AZURE_WEBHOOK_URL


env:
  global:
    - secure: "Q+LkmbQODaPDwPViC+uClnErcXPN1NtV/XPkVaB7E3JeUl2jXAsHz5tCQDQR0RAh8ril3Y4e0tDuQdlYiDxZrvXATX3hBbTy81wd2xPelBCuCpClXUJEQJCsPGtOASfab2poC0IhekvWz31AppPGSxMR2v5h3j+xEw5XY30Q0Rl1HclngyCn3bGFA9RZzr3LScqfaD6iiwjYzCZZnXmgK9ugpU4iEqkpBRPT7N0FSXXWmj3COJRUfeQNEkkUJ01D/RxjyU+xeWtLdzdsEakMD0txGXIY7aaPnZNLpWJr5Bo4bqu+DNACT2NWpoq/d6YurNG6OOksaVbhbwS6NNNIxMlJ/WUpKDYlzxcMkUpqGVRy0gHGo40JwszJ5FJAJqFRr042XlSv1W+L+DVWnCBbPgEWuGtLBbVZ+UCuDEzdr+id403LolN/23rS0MgJKQknd6FHgNlimjxwFWNsx5ky1ZvSliwrI1PRKCafuxUUnzPRw2Eug0LcGYAHm1gIOXTvKO2bZVu70wn2Jh1YjezhsQHIMo0wm3fYDFrspmKYliqxFBxN9yaMvSBL284vmzND13gyQ50ycHpev6ZzQ54Kbfb/Tco5WfxD6JLLrguJgUNIx4woEjHqz1Lgh6qrlUwPl5EUzgZLyVLzqFvPuvji6XtJm4HAHHCROFXS9b5er5w="
    - secure: "aZznTD78yfCR5HXOwk2ci5hFOEcYkG+IRTiRhm2OQ1u6XGRXSQpukwo8GlyzW2KCEYetiee0P6H3QCpRu4xSE3S+2j2hjG1eUFaRM9AKtxbhDbUHD/yEEdVv6qG2WlbUIObdism8h8YTssG5gQ+58uWrDPve4cpnHX8q5FatcGITk6+yRDSNvwPA6FIVfDKDUgdc0/OkibxnxCsq9QE9CF/qKQKk+FI7Da9+JHhhZ4lHRE3UnALTthK3AHLhuZuJuSnnnuIAkTsNPnSYk28OPV2YFb8nV7twyKvF7XpXpE0yGDxqa43ixSlJg5TXWRdAvn9KJPK/mQ1hjEL2BF79y76L3jSeSp1I9L3C8BIaCJFUiv8HYljZvrn+XmkQuMrkQXfccWZsL8eNXDPa/o4nUkrWneKmzJ3inAiKZsQ+DxMH87be4SB8qQn8JKc+FFKmKrDFI+Nm3D+dCUIykcbOdIAzYMN4viI+YrZN15c9HlNJUlPK1jOVLZbWoLBRiwF6Hv6XlV/+DPcn7WWwt3lwlLachtG8fkxqxetm0xzps7exTnoz97XEhSYotlw3m9mPeikd7o3/f7jpfgdo4unKD0lzbhmnhFKMT0YvYQfwaIGpC6VC44GBdvyqJrVowWWa95Pzx/i2R/4mtg+bYFyomKvpKwI+CiVYkK1OiWA0VeA="
    - secure: "Z47pdjKubz9JwfeCLOO8BBiyvoHdCvfG/6Py8DW9W7+QJYA86eeCT7jydgX4EDNESaSAJ1MExvXDq0rHloHxnGNBvvc44eueOwb/kzIC/tEASFRLb8qrxjOHJg7I+mwdiOtzhsG95PrhPeJDCLZ2dsNIIKharf6MIGvhS6Zem5CrdejXMRbxGj+v2p+mHhsUgXj8esYEPavklBI8VXSPfHjchYdqR5Mag8O1mS++iw4RnIEkk5iFEXcL5i1aHypubKlU83Noklx5R/eTmWzgo8VqTHqtxqsL/3W4vqNz5CY8/KY1D8e81fR4OYtTdHKrsEbzTcDU0iKQXBrg4hpaCua84MNzFihQ1UHFj1bEFTyy9yReqoEl1Tarl0n96lCK4e2QRUz+kRC8U+R83dtPp0Pav4odI2aBnR5eXwRqIFtVJanPwgQeST8Dldgw7J3tmwFoOLhqD0h8mfeCb8yCD20U5CeccF0b7PcuWyOssEFXD8NmziTQzORAm6Zod0KhbXZx4rpW5oeJ0cFVRJicxZuMw+gJIpSCc8UB45Mq6UXWJQGW0s7mYBRSBjQD1lueatttN5mZzzpeM/naMqfpoz6Jfh6bIktxXovjuUUKXdMeIItDLjZxtaEwamkfc4wkE6XbSQEoj3v2NQrgGERbUZOfkMDJi5SoRewEg5lKT9c="
    - secure: "pV++7yWMH7z+9mzzf2oYTRBxGXsu/NTd/KSskNnXzC7y1piuTvAN6hzwRkVPn2CRWURnjhNop620DGhJjwMFaNmjRL8fP3lBzIvgQboS5uPNwBNll8H+3Zy6V/y4hQEEPQ10tzJ5Fp9LF900rcEDqF47wH4EV23ggbtHi30rweHWJWXJJh1bO/TQnkxqDieKu5AX+X9/NjCAoIhcKSj46HOjGqQ1e2W1uMoRtg3b6V/w/AZsdxiPAqRyQMG0EkD/y3f543m+7ekz+NFaJBTr3XxUOs0CPDvl+BfAQAIyLFeLUeClgtE/usmoqQW4OAeTTly4/uLiBZQYANGZv0S8Ams/hkXSjlR5NPtkGBYKcuKkJM+JMebUbbxcYih5Pk/h2bAIovpWfz+GrQGe7jNSxk6BDSQeheNbJHFQLTBAYYk+kdR0at6wC/ZGaL5j1yERZ78cisJ51T63O2Ib/7QANPttf8ompOYovwjJWXgxS+XBBY8ia8bkLQ23NVwwmnclc7J1QT9EfZhNR2iyIo/jVPh6q/Fu3lDgj25McaAAu3D5f6mbtmNoKP30/NJhA/pW3PWhi4CyPm2Mmvic00FexhNlzEM3rl6bydrIRkx1nUQzaExpo+RvJ/ypEr08vRvD8BHSqbqyW50y/umpYebYA14NAROAma14dHoUeZRsN2E="