services:
- docker

branches:
  only:
    - master
    - module_9


before_script:
- echo "Test the TODO list"
- docker build --target testing-offline --tag todo-app:devops-course-starter_todoapp-test-offline .
- docker run --env-file .env.test todo-app:devops-course-starter_todoapp-test-offline
- docker build --target testing-online --tag todo-app:devops-course-starter_todoapp-test-online .
- docker run  -e DB_USERNAME=$DB_USERNAME -e DB_PASSWORD=$DB_PASSWORD -e DB_CLUSTER=$DB_CLUSTER todo-app:devops-course-starter_todoapp-test-online
      
script: 
- echo "Build the TODO list"
- docker build --target production --tag $DOCKER_USER/todo-app:$TRAVIS_COMMIT .

- echo "Push the TODO list to Docker Hub"
- echo $DOCKER_PWD | docker login --username $DOCKER_USER --password-stdin
- docker push $DOCKER_USER/todo-app:$TRAVIS_COMMIT

- echo "Push the TODO list to Heroku"
- docker pull $DOCKER_USER/todo-app:$TRAVIS_COMMIT
- docker tag $DOCKER_USER/todo-app:$TRAVIS_COMMIT registry.heroku.com/georgestodoapp/web
- heroku container:login
- docker push registry.heroku.com/georgestodoapp/web
- heroku container:release web -a georgestodoapp


env:
  global:
    - secure: "IstOGvoARYkWeOIxXW6qc3WsKFKFauLf4qpUngSQAoCn2YrAG/CTwq8IqBxW56jdaWecckB+XpwRRTVWBerFugVsd92soI9dD69Ti8K6LK89o80aXZZiYSwY52aDnxurtwP/Q8RXSrNilsYUQGxJ860OTEaWxWkJ4gAhHEkc1MPqHS85Fk9DvOzLPzeOsXaauj9EGy9RVFrgI/nHTb9U7+Q9oAFzw06JWa5vc2N3Xkh1DvczIYbyCJBPBjmrx58uwCO9q5XZT9J15KIdyKCqAUjn2mc1mYIyXVpPPXMBJl/zxTqz9p5//yb/V95f1evGom6iGpy8sMybCPLTKE2CMBQdwxuVX4ibXgf9ghKlPUfchotGP6VCMuZccRJ3S2M4LVveR9EsthK6KGSNonDp6Iqt1ITvyMeux4ZyNFhIYO6B+DL5MOGIdr+B3NoNob/USi1GWlpKwssn/1D/RQGoH/++MINBVrRkOdcWbBSvenMGK5MPIQ2IObsF48nvsOzvWbRoDssLupIC+w/FNtJ3h5BKZUnQFfvHbXQREVBOnH0XM2EE8LOavGLEwCk8hR/96QVCiWDP8KsksAd4c//f43dHwpaYQ9jxcF20lmIHVDz7N/EwL5rRkITuwG7iAxsjFJ5+p2159Bn3FqYktoyyqVef8UjE5OVsMx+1X9cA2TE="
    - secure: "pa8WfZxXXp6Szfvvxtd84yHGv1Sp6TFpl2/eUVIVP1CDs1uoiDKStApNg53J482vp8yb2BS6YYjLOpNuC21b1CRAqvbzy8zlujdtzXi2J/4HTqy5psCSm/sw/v5mzf96xeYOv9xg5B8PO1vkXcosrf0k6+nCuDhfmun17IY84BB88NqR88kFqk19MAaLPgOdA+x/YAXGYYDXWgwNCVAajn1XNaOHTzMyCbqOXqM3iAaFIF4IYj5My5MGq8LuZhfelCBQt0g64MBiMjkYKeyLNwqwxC5yh7gPFEXZpaE5FFq4tB3YnB4DGQIkP5eKaLf/9DNmxqQuTKq69nVKpo3bphy3v/n5vBDTyOC1ax/W4kB0qQZ3tw+NqfSFUFlTm4laQEeavokgE9Lk4baVStyCtcg/7BP8ZsfGs2lwD7qmCBDHMwHU7Y2hfEdQ+Rtrvw1bjFzu+jz9fc9j3sVY158Eg3taLybJg8sadVvVQty+IQ0pwsMJ+s5xLvabI9K/dAIG81LV1UBPCLIfDXlrmIANeaM3bvbxhcHQlc4hdLkf4fREe3pdz2rp2CgVg9hmk4K0+HJ0VtawWogB99E/IhBENaRgRr2j6J4SDVs7KqwLoG4Jo6scq+61gH1/PKYmVjdVabcMgvFtFGc68OY0J5W28rP1NZhtbrU/Yipzplwt5hs="
    - secure: "ainbEdWOUPMB4JngePXDuU58EN4FGbEVEnkrgv4DQPbDb2+vYVzzbKCOMOniVtch0k3bhdO7GlvIbv6dnf/xAQuGOeuIX1g0Ameo+QGfudn50mVGug2+5PRtM/VLARt2gl1yIQAMn5EyYHKwEmfSWakqCLTQRIUPBpbntcNTYxgtgsXwqH65m4ey6bQtkg3mLk+XvyDi/H/QXIWTd9N3aaXCKPdCoQuq7NPxFoCHVO2ZflDJuSVruySaqP3uPXzcR6+nfzMxXePL2eMacZcB+fseqJev002DfiQleNP1GKW2XIzB0QUn2tl7e+StoTnT9JZ1w+bfoEVWAcYJEDle+Ga5Md395KbrRrHoBFyESIeUrYEXjr+PeXR7/wmN8ZCKeJ1hXzwqMppSQ+zcuYiRqeXy76zywQUbu9kaV3X2U2aut/RClNTWqsUmeFCsM1S9QS+1msrI8Qp+nRnfTqu1pm973ufmzAy1gIWd8e4xOygq7ACnMKcxlv52VeQgvuMN5v+gQcUvyBjDFKHAnsEokOWZ+Q8HS/6LlrjoNgJlm+mookQ97tgNJdPxeRfUhpDIDEtRN5zKOJCoIPGmAWA9nxzpL97RzdyzMsb2VIqUPOshFEjQyX7qbBFDGv0VrrE0nHymaudj+aDng1d0G3onq7JDWrYqhTa3e7ZEl2CDoiM="
