services:
- docker

branches:
  only:
    - master
    - module_9


before_script:
- echo "Test the TODO list"
- docker build --target testing-offline --tag todo-app:devops-course-starter_todoapp-test-offline .
- docker run --env-file .env.test todo-app:devops-course-starter_todoapp-test-offline
- docker build --target testing-online --tag todo-app:devops-course-starter_todoapp-test-online .
- echo $DB_CONNECTION_STRING
- echo $DATA_COLLECTION
- docker run  -e DB_CONNECTION_STRING=$DB_CONNECTION_STRING -e DATA_COLLECTION=$DATA_COLLECTION todo-app:devops-course-starter_todoapp-test-online

      
script: 
- echo "Build the TODO list"
- docker build --target production --tag $DOCKER_USER/todo-app:$TRAVIS_COMMIT .

- echo "Push the TODO list to Docker Hub"
- echo $DOCKER_PWD | docker login --username $DOCKER_USER --password-stdin
- docker push $DOCKER_USER/todo-app:$TRAVIS_COMMIT

- echo "Push the TODO list to Heroku"
- docker pull $DOCKER_USER/todo-app:$TRAVIS_COMMIT
- docker tag $DOCKER_USER/todo-app:$TRAVIS_COMMIT registry.heroku.com/georgestodoapp/web
- heroku container:login
- docker push registry.heroku.com/georgestodoapp/web
- heroku container:release web -a georgestodoapp


env:
  global:
  - secure: "C1YpBtotClvmx58O2FOjUps4/++qTX/aaeRqF7iMhN64A577zmnRv0sEGu5eF9caDg5OEV4RQXwYJBhBEE8jrv+i59ZFrVbRFNFyql9J+RlKbAtZuNIAbtsfs+w7sVNXN5c7jImCr5yWu36x2TG8u+3qE2G0i/yxTYNgEKXQx14LgZKpE7pEevtpvugR+R0dWFiq+VH+OGS3X5876n6qRlwpsobza/u58/GXOgMzIdDjFeY1pdPOA0wt4217AYs5f9Bh2yZFTKih0rucPdxfUAhKHIt+/KChUZzJdF/WzCpyNXCKyYrBH5xZnqMZcfimqBm+ZT+F2JcIaK+TtqJX0AkonHYSzd9zNyK2ixl8dPJQnh1yrTkOER3WTUT1I9uE/zZXRH/ZXYG+Vl21j4QW7hnICtDBF6ZoEC1EqC2VJg7bK9Q/M0ixJZdzCTdBh/CCBVB2dT+P+5RA9gmlSTH4+yA9Wh86kKfteoOeUbuE7W/f+w6sAAwSPY1Lay6+CQEweGzn0ntncLCmNM9GjOUPDCRPrYRan8qnHGosDMnkuXUkBg665GFY+GKgtBhmMl64wM4HMp0Xd3JozAARWid4oi5XOXDXGnAiinNcWJN+OZJ6ZN3PDHQgkjz343g5AFnVUr7G5yoJ2Q6rC5KI+rVwn9jxMXo5ryRqcJFOnjkkEKY="
  - secure: "A8kHp66nAAvW7yDhigX3UKW/cUtxdWCu+n1yAMYlaCMbiVw2csWc5uupkjQIE7hc+wcUrJBZ5agY8FkdH/MUp0a1LGtHNChfAqT0QzvvOpI949A1E22rqNi2V4zybBYD8ErSd6x7TgsKk3p1wc/qh68pY7aDPiJunh6kmxhVrbfg//C2QysGKYSv2JSC9gGGksePc/1bzo/dsn2MVjxmfR3lUPZt13Fb0vZypdT7JhEE9MzTEJ3/38aKqAsPJxp6Mq1REWpB9nfvjsvirfSHMLQqUhW8NQbk+yR+WV9O0X/HQjlhawW8IGRWkZFwIcozTjITP/5mPNx7iyt41ddTkUIWbwvLBRPbRLWq/iGi5nXVTqhjtLDK9zW/IKlZny8Sxdv3/oRGWPMcd47zp2Rnd9xAlM212PJ+djhMrts72qiOR8BJDpxR+zHM2FUOq7CPITzE/D7ZZyP8sNspQhjawEJL/PuI7Er9gd5rYsQI4SgPS4L+3L5ziwTtjhdVsAiSXfT337dsRGbf3R+oo6ATfOOaf8GALqDK3Obu3awZ5lVwbp47LTtqINcc/v/hDyhPYbEHbUL92YGC/8scUhFBDcKQgCdOK3yyH9rjsHZZ4929yApbPKOF77eEOHdqZ6+6LRYwS5ELtO7ZWHKyeqQ/qc16lYwdNkyCNOG7v9vHHd4="
  