services:
- docker

branches:
  only:
    - master
    - module_9


before_script:
- echo "Test the TODO list"
- docker build --target testing-offline --tag todo-app:devops-course-starter_todoapp-test-offline .
- docker run --env-file .env.test todo-app:devops-course-starter_todoapp-test-offline
- docker build --target testing-online --tag todo-app:devops-course-starter_todoapp-test-online .
- docker run  -e DB_CONNECTION_STRING=$DB_CONNECTION_STRING -e DATA_COLLECTION=$DATA_COLLECTION todo-app:devops-course-starter_todoapp-test-online

      
script: 
- echo "Build the TODO list"
- docker build --target production --tag $DOCKER_USER/todo-app:$TRAVIS_COMMIT .

- echo "Push the TODO list to Docker Hub"
- echo $DOCKER_PWD | docker login --username $DOCKER_USER --password-stdin
- docker push $DOCKER_USER/todo-app:$TRAVIS_COMMIT

- echo "Push the TODO list to Heroku"
- docker pull $DOCKER_USER/todo-app:$TRAVIS_COMMIT
- docker tag $DOCKER_USER/todo-app:$TRAVIS_COMMIT registry.heroku.com/georgestodoapp/web
- heroku container:login
- docker push registry.heroku.com/georgestodoapp/web
- heroku container:release web -a georgestodoapp


env:
  global:
  - secure: "Dp+Z4TGEa2e6cbDwH38vVqX5YoebP3Q2sQv+aUNz/RRBhQFWiFvoRl60CktRph9YssBiGzS2d86rB/fs71ZbTM5nQXLF+mHdbdcTGnkFDgEVDpctu4cDAQcZJYm3O4qPrwtboTa6tMfJMhoVwxXiy5FrL3/D4X3sWsWpA5czB2LSDt5ElSmSBAOBwmJFvKORY1YZPeKQ2r2tEYb0pdjAcUMh7k+lT6XOsgjxu6xGjUWMggGwTzWOaclwjvK8sWIC6sugL8VqamoWfuwV8Te2IfM9GfXcqEEa5OdtlTcNqRisfGoyImCmGoAwMn4PKtfbzvlRz0vUIz2ybLsPoNGlX3SXOBCqVzElwixvTsKtwzXTt6Xc1mc8EPBqdYWrz0Fosw1gwgd3M8n4X6v9DnDHCZ1RvzCdu4X/dK+rKyNAIFfhUp42oegN+jDGpEYdhsdpx81ASnrByqz4OPJQvJTNMnRPi5qKp3yXCGLKLgmLUuj8zkaPOzoXuPz1u/0q1TwrIUmE3nH1+BqKnX33REf4Enb3IefrlxXqRBUKTgy6OvQmoY/xp0cnpzlTD3uZ0F3jvMsHTRS6uvptn8MhAjsLSdw+9pNsmnkq8JVayy6dHXU6CaCVaHwX/HtZ+Abg+5AkA1zOZ9XtLGn/QJG0OXb6SdDwkHp2rZRuYchCdTkgro0="